export { createContext, type PlanContext, type Warning } from './context.js'
export { defineOperation, type OperationDef, operationMap } from './define.js'
export { type PlanResult, planBatch, type RawOperation } from './engine.js'
export { OperationError, PatchError, RevisionRewoundError, StaleRevisionError } from './errors.js'
export { fixtureOperations } from './fixture-operations.js'
export { deepFreeze } from './freeze.js'
export { allIds } from './ids.js'
export { OPERATIONS, OPERATIONS_BY_TYPE, Operation } from './operations/index.js'
export { partialPatches } from './partial.js'
export { applyPatches, type Patch, type Path, type PathSegment } from './patch.js'
export { FolderPersistence, MemoryPersistence, type Persistence } from './persistence.js'
export * from './references.js'
export { serializeDocument } from './serialize.js'
export { type ApplyResult, type Batch, DocumentStore, kindForMime } from './store.js'
