export { createContext, type PlanContext, type Warning } from './context.js'
export { defineOperation, type OperationDef, operationMap } from './define.js'
export { type PlanResult, planBatch, type RawOperation } from './engine.js'
export { OperationError, PatchError, StaleRevisionError } from './errors.js'
export { deepFreeze } from './freeze.js'
export { allIds } from './ids.js'
export { partialPatches } from './partial.js'
export { applyPatches, type Patch, type Path, type PathSegment } from './patch.js'
export * from './references.js'
