import { expect, it } from 'vitest'
import { editor } from './harness.js'

it('sets site and page SEO in the editor and publishes it with a not-found page and a redirect', async () => {
  const { server, page, publish, saved } = await editor()
  const image = 'lacuno-about-page-preview.png'

  // Site settings save each field as it is left.
  await page.getByRole('button', { name: 'Pages', exact: true }).click()
  await page.getByRole('button', { name: 'Site settings', exact: true }).click()
  const site = page.getByRole('dialog', { name: 'Site settings' })
  const url = site.getByLabel('Public URL', { exact: true })
  await url.fill('https://example.com/')
  await url.press('Tab')
  await site.getByText('without a trailing slash').waitFor()
  await url.fill('https://example.com')
  await url.press('Tab')
  await saved()
  await site.getByRole('button', { name: 'Choose favicon', exact: true }).click()
  await page.getByRole('button', { name: `Choose ${image}`, exact: true }).click()
  await saved()
  await expect.poll(() => site.locator('.image-choice strong').textContent()).toBe(image)
  const headCode = site.getByLabel('Head code', { exact: true })
  await headCode.fill('<meta name="site-marker" content="site">')
  await headCode.press('Tab')
  await saved()
  const siteLang = site.getByLabel('Language', { exact: true })
  await siteLang.fill('English')
  await siteLang.press('Tab')
  await site.getByText('Enter a language code such as en or de-AT.').waitFor()
  await siteLang.fill('en-US')
  await siteLang.press('Tab')
  await site.getByLabel('Redirect from', { exact: true }).fill('/old')
  await site.getByLabel('Redirect to', { exact: true }).fill('/old')
  await site.getByRole('button', { name: 'Add', exact: true }).click()
  await site.getByText('cannot redirect to itself').waitFor()
  await site.getByLabel('Redirect to', { exact: true }).fill('/about')
  await site.getByRole('button', { name: 'Add', exact: true }).click()
  await saved()
  await site.getByText('/old → /about').waitFor()
  await site.getByRole('button', { name: 'Close', exact: true }).click()

  // Page settings carry the rest of the page's SEO and its code.
  await page.getByRole('button', { name: 'Settings for About', exact: true }).click()
  const settings = page.getByRole('dialog', { name: 'Page settings' })
  await settings.getByLabel('SEO description', { exact: true }).fill('About this site.')
  const lang = settings.getByLabel('Language', { exact: true })
  expect(await lang.getAttribute('placeholder')).toBe('en-US')
  await lang.fill('English')
  await settings.getByRole('button', { name: 'Save page', exact: true }).click()
  await settings.getByText('Enter a language code').waitFor()
  await lang.fill('en')
  await settings.getByLabel('Hide from search engines', { exact: true }).check()
  await settings.getByRole('button', { name: 'Choose social image', exact: true }).click()
  await page.getByRole('button', { name: `Choose ${image}`, exact: true }).click()
  await settings
    .getByLabel('Head code', { exact: true })
    .fill('<meta name="page-marker" content="about">')
  await settings.getByRole('button', { name: 'Save page', exact: true }).click()
  await saved()

  // The not-found page is one checkbox away and marked in the list.
  await page.getByRole('button', { name: 'New page', exact: true }).click()
  const create = page.getByRole('dialog', { name: 'New page' })
  await create.getByLabel('Not found page', { exact: true }).check()
  expect(await create.getByLabel('URL path', { exact: true }).inputValue()).toBe('/404')
  await create.getByText('Served for unknown addresses').waitFor()
  await create.getByRole('button', { name: 'Create page', exact: true }).click()
  // Creating a page opens it, so the list's active page is the signal, not the save state.
  const active = page.locator('.page-link.active')
  await expect.poll(() => active.textContent()).toContain('Not found')
  await active.locator('.badge').waitFor()
  await page.getByRole('button', { name: 'New page', exact: true }).click()
  expect(await create.getByLabel('Not found page', { exact: true }).isDisabled()).toBe(true)
  await create.getByRole('button', { name: 'Close', exact: true }).click()

  // Pages are served from the server's published address; the Public URL names them.
  const live = await publish()
  const publicUrl = 'https://example.com'
  const fetch = async (route: string) => await server.published!.request(`${live}${route}`)
  const text = async (route: string) => await (await fetch(route)).text()

  const about = await text('/about')
  expect(about).toContain(`<link rel="canonical" href="${publicUrl}/about">`)
  expect(about).toContain('<meta name="robots" content="noindex">')
  expect(about).toContain('<meta name="description" content="About this site.">')
  expect(about).toMatch(new RegExp(`<meta property="og:image" content="${publicUrl}/[^"]+">`))
  expect(about).toContain('<meta name="twitter:card" content="summary_large_image">')
  expect(about).toContain('<html lang="en">')
  // A language without a territory has no og:locale.
  expect(about).not.toContain('og:locale')
  expect(about).toContain('<link rel="icon" type="image/png"')
  expect(about).toContain('<meta name="site-marker" content="site">')
  expect(about).toContain('<meta name="page-marker" content="about">')
  const home = await text('/')
  expect(home).toContain('<meta name="twitter:card" content="summary">')
  // The home page keeps the site language.
  expect(home).toContain('<html lang="en-US">')
  expect(home).toContain('<meta property="og:locale" content="en_US">')

  expect(await text('/404.html')).toContain('<title>Not found</title>')
  const missing = await fetch('/missing')
  expect(missing.status).toBe(404)
  expect(await missing.text()).toContain('<title>Not found</title>')
  const sitemap = await text('/sitemap-0.xml')
  expect(sitemap).toContain(`<loc>${publicUrl}/</loc>`)
  expect(sitemap).not.toContain('/about')
  expect(sitemap).not.toContain('/404')
  expect(await text('/robots.txt')).toContain(`Sitemap: ${publicUrl}/sitemap-index.xml`)
  expect(await text('/old')).toMatch(/http-equiv="refresh" content="0;url=\/about"/)
}, 240_000)
