import type { Document } from './document.js'
import { DOCUMENT_VERSION } from './document.js'
import { BASE_BREAKPOINT_ID, type StyleDecl, styleKey } from './styles.js'
import { color, designToken, fn, kw, list, px, rem } from './values.js'

/**
 * A small but complete marketing page used by tests across packages: design tokens with a dark mode,
 * classes, a combo class, breakpoints, states, a component with a slot, and a collection list.
 */
export function fixtureDocument(): Document {
  const styles: StyleDecl[] = [
    // page
    {
      class: 'c-page',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'font-family',
      value: designToken('t-font-body'),
    },
    {
      class: 'c-page',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'color',
      value: designToken('t-fg'),
    },
    {
      class: 'c-page',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'background-color',
      value: designToken('t-bg'),
    },
    // container
    {
      class: 'c-container',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'max-width',
      value: px(1200),
    },
    {
      class: 'c-container',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'margin',
      value: list([px(0), kw('auto')]),
    },
    {
      class: 'c-container',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'padding',
      value: list([px(0), designToken('t-space-md')]),
    },
    // hero
    {
      class: 'c-hero',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'display',
      value: kw('grid'),
    },
    {
      class: 'c-hero',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'grid-template-columns',
      value: fn('repeat', [
        { type: 'unit', value: 2, unit: 'number' },
        { type: 'unit', value: 1, unit: 'fr' },
      ]),
    },
    {
      class: 'c-hero',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'gap',
      value: designToken('t-space-lg'),
    },
    {
      class: 'c-hero',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'padding-block',
      value: fn('clamp', [rem(3), { type: 'unit', value: 8, unit: 'vw' }, rem(8)]),
    },
    {
      class: 'c-hero',
      breakpoint: 'tablet',
      state: 'none',
      property: 'grid-template-columns',
      value: { type: 'unit', value: 1, unit: 'fr' },
    },
    // heading
    {
      class: 'c-heading',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'font-size',
      value: fn('clamp', [rem(2), { type: 'unit', value: 5, unit: 'vw' }, rem(4)]),
    },
    {
      class: 'c-heading',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'line-height',
      value: { type: 'unit', value: 1.1, unit: 'number' },
    },
    {
      class: 'c-heading',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'margin',
      value: px(0),
    },
    {
      class: 'c-heading',
      breakpoint: 'mobile-p',
      state: 'none',
      property: 'text-align',
      value: kw('center'),
    },
    // button and combo
    {
      class: 'c-button',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'display',
      value: kw('inline-flex'),
    },
    {
      class: 'c-button',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'padding',
      value: list([designToken('t-space-sm'), designToken('t-space-md')]),
    },
    {
      class: 'c-button',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'border-radius',
      value: designToken('t-radius'),
    },
    {
      class: 'c-button',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'text-decoration',
      value: kw('none'),
    },
    {
      class: 'c-button',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'transition',
      value: list([kw('background-color'), { type: 'unit', value: 150, unit: 'ms' }]),
    },
    {
      class: 'c-button',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'hover',
      property: 'background-color',
      value: designToken('t-surface-muted'),
    },
    {
      class: 'c-button',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'focus-visible',
      property: 'outline',
      value: list([px(2), kw('solid'), designToken('t-brand')]),
    },
    {
      class: 'c-button-primary',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'background-color',
      value: designToken('t-brand'),
    },
    {
      class: 'c-button-primary',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'color',
      value: color('#fff'),
    },
    {
      class: 'c-button-primary',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'hover',
      property: 'background-color',
      value: designToken('t-brand-hover'),
    },
    // local override on the hero heading
    {
      class: 'l-hero-title',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'letter-spacing',
      value: { type: 'unit', value: -0.02, unit: 'em' },
    },
    // card component
    {
      class: 'c-card',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'border',
      value: list([px(1), kw('solid'), designToken('t-border')]),
    },
    {
      class: 'c-card',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'border-radius',
      value: designToken('t-radius'),
    },
    {
      class: 'c-card',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'padding',
      value: designToken('t-space-md'),
    },
    {
      class: 'c-card',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'before',
      property: 'content',
      value: { type: 'raw', value: '""' },
    },
    {
      class: 'c-post-grid',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'display',
      value: kw('grid'),
    },
    {
      class: 'c-post-grid',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'grid-template-columns',
      value: fn('repeat', [
        kw('auto-fill'),
        fn('minmax', [px(280), { type: 'unit', value: 1, unit: 'fr' }]),
      ]),
    },
    {
      class: 'c-post-grid',
      breakpoint: BASE_BREAKPOINT_ID,
      state: 'none',
      property: 'gap',
      value: designToken('t-space-md'),
    },
  ]

  const doc: Document = {
    version: DOCUMENT_VERSION,
    revision: 0,
    site: {
      name: 'Fixture Co',
      locale: 'en',
      modes: [
        { id: 'light', label: 'Light', default: true },
        {
          id: 'dark',
          label: 'Dark',
          selector: '[data-theme="dark"]',
          media: '(prefers-color-scheme: dark)',
        },
      ],
      fonts: [{ family: 'system-ui', source: 'system', fallback: 'sans-serif' }],
    },
    pages: {
      'p-home': {
        id: 'p-home',
        name: 'Home',
        path: '/',
        root: 'n-home',
        seo: { title: 'Fixture Co', description: 'A fixture site.' },
      },
      'p-post': {
        id: 'p-post',
        name: 'Post',
        path: '/blog/[slug]',
        root: 'n-post',
        collection: 'col-posts',
      },
    },
    folders: {},
    nodes: {
      'n-home': {
        id: 'n-home',
        type: 'element',
        tag: 'main',
        parent: null,
        children: ['n-hero', 'n-posts'],
        classes: ['c-page'],
        semantic: { role: 'page' },
      },
      'n-hero': {
        id: 'n-hero',
        type: 'element',
        tag: 'section',
        parent: 'n-home',
        children: ['n-hero-inner'],
        classes: ['c-container', 'c-hero'],
        semantic: { role: 'hero', constraints: ['above-fold'] },
      },
      'n-hero-inner': {
        id: 'n-hero-inner',
        type: 'element',
        tag: 'div',
        parent: 'n-hero',
        children: ['n-hero-title', 'n-hero-image', 'n-hero-cta'],
        classes: [],
      },
      'n-hero-title': {
        id: 'n-hero-title',
        type: 'text',
        tag: 'h1',
        parent: 'n-hero-inner',
        children: [],
        classes: ['c-heading', 'l-hero-title'],
        text: {
          type: 'doc',
          content: [
            {
              type: 'paragraph',
              content: [{ type: 'text', text: 'Design it. Publish it. Own it.' }],
            },
          ],
        },
      },
      'n-hero-image': {
        id: 'n-hero-image',
        type: 'element',
        tag: 'img',
        parent: 'n-hero-inner',
        children: [],
        classes: [],
        attrs: {
          src: { type: 'asset', asset: 'a-hero' },
          alt: { type: 'static', value: 'A blue rectangle standing in for a hero image' },
          loading: { type: 'static', value: 'eager' },
        },
      },
      'n-hero-cta': {
        id: 'n-hero-cta',
        type: 'text',
        tag: 'a',
        parent: 'n-hero-inner',
        children: [],
        classes: ['c-button', 'c-button-primary'],
        attrs: { href: { type: 'static', value: '/blog' } },
        text: {
          type: 'doc',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Read the blog' }] }],
        },
      },
      'n-posts': {
        id: 'n-posts',
        type: 'collection-list',
        tag: 'div',
        parent: 'n-home',
        children: ['n-post-card'],
        classes: ['c-container', 'c-post-grid'],
        collection: 'col-posts',
        query: { sort: [{ field: 'f-date', direction: 'desc' }], limit: 6 },
      },
      'n-post-card': {
        id: 'n-post-card',
        type: 'component',
        parent: 'n-posts',
        children: [],
        classes: [],
        component: 'cmp-card',
        props: { title: { type: 'field', field: 'f-title' } },
      },
      // card component subtree
      'n-card': {
        id: 'n-card',
        type: 'element',
        tag: 'article',
        parent: null,
        children: ['n-card-title', 'n-card-slot'],
        classes: ['c-card'],
      },
      'n-card-title': {
        id: 'n-card-title',
        type: 'text',
        tag: 'h3',
        parent: 'n-card',
        children: [],
        classes: [],
        text: { type: 'prop', prop: 'title' },
      },
      'n-card-slot': {
        id: 'n-card-slot',
        type: 'slot',
        name: 'body',
        parent: 'n-card',
        children: [],
        classes: [],
      },
      // post page
      'n-post': {
        id: 'n-post',
        type: 'element',
        tag: 'main',
        parent: null,
        children: ['n-post-title', 'n-post-body', 'n-video', 'n-embed'],
        classes: ['c-page', 'c-container'],
      },
      'n-post-title': {
        id: 'n-post-title',
        type: 'text',
        tag: 'h1',
        parent: 'n-post',
        children: [],
        classes: ['c-heading'],
        text: { type: 'field', field: 'f-title' },
      },
      'n-post-body': {
        id: 'n-post-body',
        type: 'text',
        tag: 'div',
        parent: 'n-post',
        children: [],
        classes: [],
        text: { type: 'field', field: 'f-body' },
      },
      'n-video': {
        id: 'n-video',
        type: 'element',
        tag: 'video',
        parent: 'n-post',
        children: [],
        classes: [],
        attrs: {
          src: { type: 'asset', asset: 'a-clip' },
          controls: { type: 'static', value: true },
          playsinline: { type: 'static', value: true },
        },
      },
      'n-embed': {
        id: 'n-embed',
        type: 'embed',
        parent: 'n-post',
        children: [],
        classes: [],
        html: '<blockquote>Embedded quote</blockquote>',
      },
    },
    classes: {
      'c-page': { id: 'c-page', kind: 'class', name: 'page' },
      'c-container': { id: 'c-container', kind: 'class', name: 'container' },
      'c-hero': { id: 'c-hero', kind: 'class', name: 'hero' },
      'c-heading': { id: 'c-heading', kind: 'class', name: 'heading' },
      'c-button': { id: 'c-button', kind: 'class', name: 'button' },
      'c-button-primary': {
        id: 'c-button-primary',
        kind: 'class',
        name: 'primary',
        combo: ['c-button'],
      },
      'c-card': { id: 'c-card', kind: 'class', name: 'card' },
      'c-post-grid': { id: 'c-post-grid', kind: 'class', name: 'post-grid' },
      'l-hero-title': { id: 'l-hero-title', kind: 'local' },
    },
    styles: Object.fromEntries(styles.map((s) => [styleKey(s), s])),
    breakpoints: {
      [BASE_BREAKPOINT_ID]: { id: BASE_BREAKPOINT_ID, label: 'Desktop' },
      tablet: { id: 'tablet', label: 'Tablet', maxWidth: 991 },
      'mobile-l': { id: 'mobile-l', label: 'Mobile landscape', maxWidth: 767 },
      'mobile-p': { id: 'mobile-p', label: 'Mobile portrait', maxWidth: 479 },
    },
    designTokens: {
      't-font-body': {
        id: 't-font-body',
        name: 'font.body',
        group: 'typography',
        values: { light: { type: 'raw', value: 'Inter, system-ui, sans-serif' } },
      },
      't-fg': {
        id: 't-fg',
        name: 'color.fg',
        group: 'color',
        values: { light: color('#111'), dark: color('#eee') },
      },
      't-bg': {
        id: 't-bg',
        name: 'color.bg',
        group: 'color',
        values: { light: color('#fff'), dark: color('#111') },
      },
      't-brand': {
        id: 't-brand',
        name: 'color.brand',
        group: 'color',
        values: { light: color('#3b5bdb') },
      },
      't-brand-hover': {
        id: 't-brand-hover',
        name: 'color.brand.hover',
        group: 'color',
        values: { light: color('#2f4ac0'), dark: color('#5c7cfa') },
      },
      't-surface-muted': {
        id: 't-surface-muted',
        name: 'color.surface.muted',
        group: 'color',
        values: { light: color('#f1f3f5'), dark: color('#222') },
      },
      't-border': {
        id: 't-border',
        name: 'color.border',
        group: 'color',
        values: { light: color('#dee2e6'), dark: color('#333') },
      },
      't-space-sm': {
        id: 't-space-sm',
        name: 'space.sm',
        group: 'spacing',
        values: { light: rem(0.5) },
      },
      't-space-md': {
        id: 't-space-md',
        name: 'space.md',
        group: 'spacing',
        values: { light: rem(1) },
      },
      't-space-lg': {
        id: 't-space-lg',
        name: 'space.lg',
        group: 'spacing',
        values: { light: rem(2) },
      },
      't-radius': { id: 't-radius', name: 'radius.md', group: 'radius', values: { light: px(8) } },
    },
    components: {
      'cmp-card': {
        id: 'cmp-card',
        name: 'Card',
        root: 'n-card',
        props: [{ name: 'title', type: 'string', label: 'Title' }],
      },
    },
    collections: {
      'col-posts': {
        id: 'col-posts',
        name: 'Posts',
        slug: 'posts',
        slugField: 'f-slug',
        fields: [
          { id: 'f-title', name: 'title', label: 'Title', type: 'text', required: true },
          { id: 'f-slug', name: 'slug', label: 'Slug', type: 'slug', required: true },
          { id: 'f-date', name: 'date', label: 'Date', type: 'date' },
          { id: 'f-body', name: 'body', label: 'Body', type: 'richtext' },
          {
            id: 'f-status',
            name: 'status',
            label: 'Status',
            type: 'option',
            options: [{ value: 'draft', label: 'Draft' }, { value: 'published' }],
          },
        ],
      },
    },
    assets: {
      'a-hero': {
        id: 'a-hero',
        name: 'hero.png',
        kind: 'image',
        hash: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
        mime: 'image/png',
        size: 0,
        width: 1200,
        height: 800,
        alt: 'Hero image',
      },
      'a-clip': {
        id: 'a-clip',
        name: 'clip.mp4',
        kind: 'video',
        hash: 'fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210',
        mime: 'video/mp4',
        size: 0,
      },
    },
    entries: {
      'col-posts': [
        {
          id: 'e-1',
          fields: {
            'f-title': 'Hello world',
            'f-slug': 'hello-world',
            'f-date': '2026-09-01',
            'f-status': 'published',
            'f-body': {
              type: 'doc',
              content: [
                { type: 'paragraph', content: [{ type: 'text', text: 'The first post.' }] },
              ],
            },
          },
        },
        {
          id: 'e-2',
          fields: {
            'f-title': 'Second post',
            'f-slug': 'second-post',
            'f-date': '2026-09-05',
            'f-status': 'published',
          },
        },
        {
          id: 'e-3',
          fields: {
            'f-title': 'Third post',
            'f-slug': 'third-post',
            'f-date': '2026-09-10',
            'f-status': 'draft',
          },
        },
      ],
    },
    redirects: [{ from: '/old-blog', to: '/blog', status: 301 }],
  }
  return doc
}
